### ISSUE TITLE
java.lang.IllegalStateException: Module entity with name: exoplayer-kotlin should be available

### ISSUE THREAD

**Issue by iiasceri** [yoobi/exoplayer-kotlin#8]
java.lang.IllegalStateException: Module entity with name: exoplayer-kotlin should be available

**Comment by yoobi** [comment]
Hello,

For which module do you have this issue ?

**Comment by iiasceri** [comment]
cloned repo and opened I've used another project for my tests ExoPlayerSample

**Comment by yoobi** [comment]
Looks like it was because `rootProject.name` and folder name was different
https://youtrack.jetbrains.com/issue/IDEA-317606/Changing-only-the-case-of-the-Gradle-root-project-name-causes-exception-while-importing-project-java.lang.IllegalStateException

It should be fix now. Please pull and restart your IDE.

**Comment by yoobi** [comment]
Hello, I'm closing the issue, don't hesitate to open it again if the issue persist
